### ISSUE TITLE
Ne pas afficher l'ip autorisée sur la page de refus

### ISSUE THREAD

**Issue by rtorrente** [guirem/plugin-autologin#5]
Pour des raisons de sécurité, je pense qu'il ne faudrait pas ajouter l'ip autorisée sur la page qui s'affiche lorsque l'ip n'est pas celle autorisée.
Cela rendra un IP Spoofing plus difficile

**Comment by guirem** [comment]
Je suis ok avec toi. Ce sera enlevé dans le prochain commit.
