### ISSUE TITLE
Rendre activable/désactivable la réponse à l'URL externe

### ISSUE THREAD

**Issue by rtorrente** [guirem/plugin-autologin#6]
Ce plugin ayant principalement vocation à être utilisé sur le réseau local, il serait interessant de pouvoir activer ou désactiver la réponse sur l'URL externe. 
Pour des raisons de sécurité, il peut être intéressant qu'on ne puisse pas voir que le plugin est activé depuis l'extérieur et que le plugin ne s'expose pas inutilement à l'extérieur. 
En cas de faille détectée, il serait en effet plus facile de l'utiliser

**Comment by guirem** [comment]
La gestion de la sécurité est déjà faite au niveau de l'utilisateur (et donc du core Jeedom) donc je ne vois pas l’intérêt de ré-implémenter ce point.  Il est possible de restreindre un utilisateur à une utilisation locale uniquement.

En cas de faille détectée, il est possible de désactiver l'utilisateur et/ou régénérer une clé api qui rendra caduque tous les liens du plugin diffusés.

Je rajoute quand même une section dans la doc pour préciser ce point.

La notion de réseau local est d'ailleurs très vague surtout pour une utilisation hors particulier (réseau local étendu, VPN...).
